#!/bin/sh
#SBATCH -w gpu01 --gpus=1 --cpus-per-gpu=16 --mem-per-gpu=5GB -J gen -o /home/nnthao/lntuong/FDA-v4/std/gen-out -e /home/nnthao/lntuong/FDA-v4/std/gen-err --time=15

cd ~/lntuong/FDA-v4

srun python generate_image.py \
    --network /media/nnthao/MAT/saved_model/MAT-and-best_models/cswint_v4-network-snapshot-000440_5m24_best.pkl \
    --dpath /media/nnthao/MAT/Data/CelebA-HQ/CelebA-HQ-val_img/ \
    --mpath /media/nnthao/MAT/Data/CelebA-HQ/masks_small_celebahq_val_512 \
    --outdir /media/nnthao/MAT/Data/CelebA-HQ/cswintv4_5m24_sgen_s240_samples