#!/bin/sh
#SBATCH -w gpu01 --gpus=1 --cpus-per-gpu=16 --mem-per-gpu=10GB -J gen --time=12:00:00

cd ~/lntuong/FDA-v6

CUBLAS_WORKSPACE_CONFIG=:4096:8 srun python generate_image.py \
    --network /media02/nnthao01/MAT/saved_model/cswint_v62/13-train840_5400-resuming12-41h10m/network-snapshot-000560_good.pkl \
    --dpath /media/nnthao/MAT/Data/CelebA-HQ/CelebA-HQ-val_img \
    --mpath /media/nnthao/MAT/Data/CelebA-HQ/masks_small_celebahq_val_512 \
    --outdir /media/nnthao/MAT/Data/CelebA-HQ/cswintv62_5m12_sgen_s240_samples