#!/bin/sh
#SBATCH -w gpu01 --gres=gpu:2 --cpus-per-gpu=24 --mem-per-gpu=20GB -J train --time=2-00:00:00
#SBATCH -o /home/nnthao/lntuong/FDA-v6/std/train-out -e /home/nnthao/lntuong/FDA-v6/std/train-err

cd ~/lntuong/FDA-v6

srun python -W ignore train.py \
    --outdir=/media/nnthao/MAT/checkpoint_model/cswint_v62 \
    --gpus=2 \
    --snap=10 \
    --batch=8 \
    --kimg=200 \
    --metrics=fid2993_full \
    --data=/media/nnthao/MAT/Data/CelebA-HQ/CelebA-HQ-img \
    --data_val=/media/nnthao/MAT/Data/CelebA-HQ/CelebA-HQ-val_img \
    --dataloader=datasets.dataset_512.ImageFolderMaskDataset \
    --mirror=True \
    --cond=False \
    --cfg=celeba512 \
    --aug=noaug \
    --generator=networks.mat_v62.Generator \
    --discriminator=networks.mat_v62.Discriminator \
    --loss=losses.loss.TwoStageLoss \
    --pr=0.1 \
    --pl=False \
    --truncation=0.5 \
    --style_mix=0.5 \
    --ema=10 \
    --lr=0.001 \
    --resume=/media/nnthao/MAT/checkpoint_model/cswint_v62/00001-CelebA-HQ-img-mirror-celeba512-mat_v62-lr0.001-TwoStageLoss-pr0.1-nopl-kimg320-batch8-tc0.5-sm0.5-ema10-noaug-resumecustom/network-snapshot-000120.pkl